config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :puzzles, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:new, :create]
  end
  get   'my_puzzles', to: 'puzzles#my_puzzles'
  get   'my_bookings', to: 'bookings#my_bookings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :puzzle

  default_scope { order(created_at: :desc) }
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
  validates :title, presence: true
  validates :size, presence: true, numericality: { only_integer: true }

  has_one_attached :photo

  validates :user, presence: true
  validates :price, presence: true, numericality: { only_integer: true }

  belongs_to :user

  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  default_scope { order(created_at: :desc) }

  include PgSearch::Model
  pg_search_scope :search_by_title_description_and_size,
    against: [ :title, :description, :size ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :puzzles, dependent: :destroy

  has_many :bookings

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  def after_sign_in_path_for(resource)
    puzzles_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @puzzle = Puzzle.find(params[:puzzle_id])
    @booking = Booking.new
  end

  def create
    @puzzle = Puzzle.find(params[:puzzle_id])
    @booking = Booking.new(booking_params)
    @booking.puzzle = @puzzle
    if user_signed_in?
      @booking.user = current_user
      @booking.save

      redirect_to my_bookings_path
    else
      redirect_to new_user_session_url
    end
  end

  def my_bookings
    @bookings = Booking.where(user_id: current_user.id)
    @user = current_user
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home,:index, :show] #what else we can see??

  def home
  end

  def index
  end

  def show
  end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  def index
    if params[:query].present?
      @puzzles = Puzzle.search_by_title_description_and_size(params[:query])
    else
      @puzzles = Puzzle.all
    end

    @markers = @puzzles.geocoded.map do |puzzle|
      {
        lat: puzzle.latitude,
        lng: puzzle.longitude,
        infoWindow: render_to_string(partial: "shared/info_window", locals: { puzzle: puzzle }),
        image_url: helpers.asset_url('puzzle-marker.png')
      }
    end
  end

  def show
    @puzzle = Puzzle.find(params[:id])
    @booking = Booking.new
  end

  def new
    @puzzle = Puzzle.new
  end

  def create
    @puzzle = Puzzle.new(puzzle_params)
    @puzzle.user = current_user
    if @puzzle.save
      redirect_to my_puzzles_path
    else
      render :new
    end
  end

  def my_puzzles
    @puzzles = Puzzle.where(user_id: current_user.id)
    @user = current_user
  end

  private

  def puzzle_params
    params.require(:puzzle).permit(:title, :size, :description, :photo, :price, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/my_bookings.html.erb
<div class="container">
  <h1 class="mt-3"><%= @user.first_name %>'s Bookings</h1>
  <div class="row">
    <div class="col-7">
      <%= render 'shared/bookings' %>
    </div>
    <div class="col-5">
      <div class="card m-3 p-3">
        <h2>General rules</h2>
        <p><i class="fas fa-puzzle-piece pink"></i> Be good</p>
        <p><i class="fas fa-puzzle-piece pink"></i> Love other people</p>
        <p><i class="fas fa-puzzle-piece pink"></i> Wear a mask</p>
        <p><i class="fas fa-puzzle-piece pink"></i> Don't destroy the puzzles</p>
        <p><i class="fas fa-puzzle-piece pink"></i> Don’t loose pieces</p>
        <p><i class="fas fa-puzzle-piece pink"></i> Don’t eat or drink on the puzzle</p>
        <p><i class="fas fa-puzzle-piece pink"></i> Don’t look back</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <header><%= render 'shared/navbar' %></header>
    <main>
      <%= render 'shared/flashes' %>

      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.6)), url(https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1494059980473-813e73ee784b%3Fcrop%3Dentropy%26cs%3Dtinysrgb%26fit%3Dmax%26fm%3Djpg%26ixid%3DMnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjE4MTE2NDY2%26ixlib%3Drb-1.2.1%26q%3D80%26w%3D1080);">
  <div class="container">
    <h1>Find the best Puzzle</h1>
    <%= link_to 'Discover the offers', puzzles_path, class: "btn btn-warning"  %>
  </div>
</div>

app/views/puzzles/index.html.erb
<div class="d-flex">
  <div class="container">
    <div class="cards">
      <div class="m-3">
        <h1><%= link_to "Rent a Puzzle", puzzles_path %></h1>
        <%= render 'shared/searchbar' %>
      </div>
      <%= render 'shared/list' %>
    </div>
  </div>
  <div id="map"
    style="height: 100vh; width: 80vw;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/puzzles/my_puzzles.html.erb
<div class="container">
  <h1 class="mt-3"><%= @user.first_name %>'s Puzzles</h1>

  <%= render 'shared/list' %>
</div>

app/views/puzzles/new.html.erb
<div class="container">
  <h2 class="m-3">Create a Puzzle Listing</h2>

  <%= render 'shared/form', puzzle: @puzzle %>
</div>

app/views/puzzles/show.html.erb
<div class="container">
  <h1 class="mt-3"><%= @puzzle.title %></h1>
  <p><%= @puzzle.size %> Pieces</p>
  <div class="row">

    <div class="col-8">
      <div class="card m-3">
        <div class="card-left" style="background-image: url(<%= cl_image_path @puzzle.photo.attached? ? cl_image_path(@puzzle.photo.key) : asset_path('puzzle-placeholder.png'), alt: @puzzle.title %>)"></div>
      </div>
      <div class="card m-3 card-right">
        <div>
          <h3>Description:</h3>
          <%= @puzzle.description %>
        </div>
        <div style="margin-top: 12px">
          <p><i class="fas fa-map-marker-alt"></i> <%= @puzzle.address.split.last %> </p>
        </div>
      </div>
    </div>

    <%= render 'shared/booking-form' %>

  </div>
</div>

app/views/shared/_booking-form.html.erb
<div class="col-4">
  <div class="card m-3 card-right">
    <%= simple_form_for [@puzzle, @booking] do |f| %>
      <div class="form-inputs" oninput="computeTotalPrice()">
        <%= f.input :start_date %>
        <%= f.input :end_date %>
      </div>

      <div>
        <%= f.submit 'Confirm your Booking' , class: 'btn btn-primary mb-3'%>
      <div>
    <% end %>
    <p>Price per day: <span id="price-per-day"><%= @puzzle.price %></span> CHF</p>
    <p> <strong> Total price: <span id="total-price"></span> CHF</strong></p>
  </div>
</div>

app/views/shared/_bookings.html.erb
<% @bookings.each do |booking| %>
  <div class="card card-list m-3">
    <div class="d-flex">
      <div class="card-image"><%= cl_image_tag booking.puzzle.photo.attached? ? cl_image_path(booking.puzzle.photo.key) : asset_path('puzzle-placeholder.png'), alt: booking.puzzle.title %></div>
        <div class="card-body pl-3">
          <h3 class="card-title mb-2"><%= link_to booking.puzzle.title, puzzle_path(booking.puzzle_id) %></h3>
          <p> Total price: <%= (booking.end_date.to_date - booking.start_date.to_date + 1).to_i * booking.puzzle.price %> CHF</p>
          <p><i class="far fa-calendar-check"></i> <%= booking.start_date %></p>
          <p><i class="far fa-calendar-times"></i> <%= booking.end_date %> </p>
          <p><i class="fas fa-map-marker-alt"></i> <%= booking.puzzle.address %> </p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-text">
    Follow us on social media
  </div>
  <div class="footer-links">
    <%= link_to "https://www.instagram.com" do %>
      <i class="fab fa-instagram"></i>
    <% end %>
    <%= link_to "https://www.facebook.com" do %>
      <i class="fab fa-facebook"></i>
    <% end %>
    <%= link_to "https://twitter.com" do %>
      <i class="fab fa-twitter"></i>
    <% end %>
  </div>
</footer>

app/views/shared/_form.html.erb
<div class="card m-3 p-5">
  <%= simple_form_for(@puzzle) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :title, placeholder: 'e.g. Cats' %>
      <%= f.input :size,  placeholder: 'e.g. 1000' %>
      <%= f.input :description, placeholder: 'Enter a comprehensive description of the product'  %>
      <%= f.input :address, placeholder: 'e.g. Bellerivestrasse 1, 8008 Zürich' %>
      <%= f.input :price, placeholder: 'CHF/day' %>
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Add a Puzzle", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/shared/_info_window.html.erb
<h2 class="map-popup"><%= link_to puzzle.title, puzzle_path(puzzle.id) %></h2>
<h6><%= puzzle.address.split.last %></h6>
<div> <%= cl_image_tag puzzle.photo.attached? ? cl_image_path(puzzle.photo.key) : asset_path('puzzle-placeholder.png'), alt: puzzle.title, width: 200 %></div>

app/views/shared/_list.html.erb
<% @puzzles.each do |puzzle| %>
  <div class="card card-list m-3">
    <div class="d-flex">
      <div class="card-image"> <%= cl_image_tag puzzle.photo.attached? ? cl_image_path(puzzle.photo.key) : asset_path('puzzle-placeholder.png'), alt: puzzle.title %></div>
      <div class="card-body pl-3">
        <h5 class="card-title mb-2"><%= link_to puzzle.title, puzzle_path(puzzle.id) %></h5>
        <h6 class="card-subtitle text-muted"><%= puzzle.size %> Pieces</h6>
        <p class="card-text my-2"><i class="fas fa-map-marker-alt"></i> <%= puzzle.address.split.last %></p>
        <p class="card-text"><strong><%= puzzle.price %>CHF</strong>/day</p>
        <i class="fas fa-star" style="color: #FFC65A"></i> <%= puzzle.rating %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-puzzle-piece" id="logo"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Puzzles", puzzles_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.attached? ? cl_image_path(current_user.photo.key) : asset_path('lady-avatar-1632967-640x640.jpg'), class: 'avatar' %>
          <i class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add a Puzzle", new_puzzle_path, class: "dropdown-item" %>
            <%= link_to "My puzzles", my_puzzles_path, class: "dropdown-item" %>
            <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="d-flex">
  <div class="search">
  <%= form_tag puzzles_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a Puzzle"
    %>
  </div>
  <div class="search-submit">
    <%= button_tag type: 'submit', class: "button my-button" do %>
      <i class="fas fa-search" aria-hidden="true"></i>
    <% end %>
  </div>
  <% end %>
</div>